window.CONTACT_GAME_CONFIG = {
  game: {
    singleLevelOnly: true,
    maxLevel: 4,
    levelTargets: {
      level1: 200,
      level2: 400,
      level3: 400,
      level4: 1000,
    },
    levelUpLifeBonus: 1,
    perimeterScorePenalty: 180,
    perimeterDropLevel: 3,
    splitterBrickMax: 5,
    catcherHoldSeconds: 0.09,
    catcherRedirectSpreadPiFactor: 0.36,
  },
  performance: {
    simulationStep: 0.008333333333333333,
    maxFrameDelta: 0.25,
    chromePerfModeEnabled: true,
    maxSimStepsDesktop: 20,
    maxSimStepsChrome: 10,
    deformationStrideDesktop: 1,
    deformationStrideChrome: 3,
    enableRelativityLensingDesktop: true,
    enableRelativityLensingInChrome: false,
    drawMeshLinksDesktop: true,
    drawMeshLinksInChrome: false,
    forceLowPowerMode: false,
  },
  render: {
    raster: {
      sizeMin: 0.24,
      sizeMax: 0.92,
      openThreshold: 0.42,
      magentaThreshold: 0.93,
    },
  },
};
