const browserGlobals = [
  'AbortController',
  'Blob',
  'CSS',
  'CustomEvent',
  'DOMParser',
  'Element',
  'Event',
  'FileReader',
  'FormData',
  'getComputedStyle',
  'HTMLElement',
  'Image',
  'IntersectionObserver',
  'MutationObserver',
  'Node',
  'ResizeObserver',
  'URL',
  'URLSearchParams',
  'WebSocket',
  'cancelAnimationFrame',
  'clearInterval',
  'clearTimeout',
  'console',
  'document',
  'fetch',
  'history',
  'localStorage',
  'location',
  'matchMedia',
  'navigator',
  'performance',
  'PopStateEvent',
  'queueMicrotask',
  'requestAnimationFrame',
  'sessionStorage',
  'setInterval',
  'setTimeout',
  'window',
].reduce((globals, name) => ({ ...globals, [name]: 'readonly' }), {})

export default [
  {
    ignores: ['dist/**', 'public/**', 'src/data/runtimeArtifacts.js'],
  },
  {
    files: ['src/**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: browserGlobals,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    rules: {
      'no-constant-binary-expression': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-debugger': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-fallthrough': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-redeclare': 'error',
      'no-self-assign': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
]
